using System.ComponentModel;

namespace Developer.ExtensionCore.Enums
{
    public enum EnumCountryCulture
    {
        [Description("aa-DJ")]
        Afar_Djibouti = 0,
        [Description("aa-ER")]
        Afar_Eritrea,
        [Description("aa-ET")]
        Afar_Ethiopia,
        [Description("af-NA")]
        Afrikaans_Namibia,
        [Description("af-ZA")]
        Afrikaans_South_Africa,
        [Description("agq-CM")]
        Aghem_Cameroon,
        [Description("ak-GH")]
        Akan_Ghana,
        [Description("am-ET")]
        Amharic_Ethiopia,
        [Description("ar-001")]
        Arabic_World,
        [Description("ar-AE")]
        Arabic_United_Arab_Emirates,
        [Description("ar-BH")]
        Arabic_Bahrain,
        [Description("ar-DJ")]
        Arabic_Djibouti,
        [Description("ar-DZ")]
        Arabic_Algeria,
        [Description("ar-EG")]
        Arabic_Egypt,
        [Description("ar-ER")]
        Arabic_Eritrea,
        [Description("ar-IL")]
        Arabic_Israel,
        [Description("ar-IQ")]
        Arabic_Iraq,
        [Description("ar-JO")]
        Arabic_Jordan,
        [Description("ar-KM")]
        Arabic_Comoros,
        [Description("ar-KW")]
        Arabic_Kuwait,
        [Description("ar-LB")]
        Arabic_Lebanon,
        [Description("ar-LY")]
        Arabic_Libya,
        [Description("ar-MA")]
        Arabic_Morocco,
        [Description("ar-MR")]
        Arabic_Mauritania,
        [Description("ar-OM")]
        Arabic_Oman,
        [Description("ar-PS")]
        Arabic_Palestinian_Authority,
        [Description("ar-QA")]
        Arabic_Qatar,
        [Description("ar-SA")]
        Arabic_Saudi_Arabia,
        [Description("ar-SD")]
        Arabic_Sudan,
        [Description("ar-SO")]
        Arabic_Somalia,
        [Description("ar-SS")]
        Arabic_South_Sudan,
        [Description("ar-SY")]
        Arabic_Syria,
        [Description("ar-TD")]
        Arabic_Chad,
        [Description("ar-TN")]
        Arabic_Tunisia,
        [Description("ar-YE")]
        Arabic_Yemen,
        [Description("arn-CL")]
        Mapuche_Chile,
        [Description("as-IN")]
        Assamese_India,
        [Description("asa-TZ")]
        Asu_Tanzania,
        [Description("ast-ES")]
        Asturian_Spain,
        [Description("az-Cyrl-AZ")]
        Azerbaijani_Cyrillic_Azerbaijan,
        [Description("az-Latn-AZ")]
        Azerbaijani_Latin_Azerbaijan,
        [Description("ba-RU")]
        Bashkir_Russia,
        [Description("bas-CM")]
        Basaa_Cameroon,
        [Description("be-BY")]
        Belarusian_Belarus,
        [Description("bem-ZM")]
        Bemba_Zambia,
        [Description("bez-TZ")]
        Bena_Tanzania,
        [Description("bg-BG")]
        Bulgarian_Bulgaria,
        [Description("bm-Latn-ML")]
        Bamanankan_Latin_Mali,
        [Description("bn-BD")]
        Bangla_Bangladesh,
        [Description("bn-IN")]
        Bangla_India,
        [Description("bo-CN")]
        Tibetan_China,
        [Description("bo-IN")]
        Tibetan_India,
        [Description("br-FR")]
        Breton_France,
        [Description("brx-IN")]
        Bodo_India,
        [Description("bs-Cyrl-BA")]
        Bosnian_Cyrillic_Bosnia__Herzegovina,
        [Description("bs-Latn-BA")]
        Bosnian_Latin_Bosnia__Herzegovina,
        [Description("byn-ER")]
        Blin_Eritrea,
        [Description("ca-AD")]
        Catalan_Andorra,
        [Description("ca-ES")]
        Catalan_Spain,
        [Description("ca-ES-valencia")]
        Catalan_Spain_Valencian,
        [Description("ca-FR")]
        Catalan_France,
        [Description("ca-IT")]
        Catalan_Italy,
        [Description("ccp-Cakm-BD")]
        Chakma_Chakma_Bangladesh,
        [Description("ccp-Cakm-IN")]
        Chakma_Chakma_India,
        [Description("ce-RU")]
        Chechen_Russia,
        [Description("ceb-Latn-PH")]
        Cebuano_Latin_Philippines,
        [Description("cgg-UG")]
        Chiga_Uganda,
        [Description("chr-Cher-US")]
        Cherokee_Cherokee_United_States,
        [Description("ku-Arab-IQ")]
        Kurdish_Arabic_Iraq,
        [Description("ku-Arab-IR")]
        Kurdish_Arabic_Iran,
        [Description("co-FR")]
        Corsican_France,
        [Description("cs-CZ")]
        Czech_Czechia,
        [Description("cu-RU")]
        Church_Slavic_Russia,
        [Description("cy-GB")]
        Welsh_United_Kingdom,
        [Description("da-DK")]
        Danish_Denmark,
        [Description("da-GL")]
        Danish_Greenland,
        [Description("dav-KE")]
        Taita_Kenya,
        [Description("de-AT")]
        German_Austria,
        [Description("de-BE")]
        German_Belgium,
        [Description("de-CH")]
        German_Switzerland,
        [Description("de-DE")]
        German_Germany,
        [Description("de-IT")]
        German_Italy,
        [Description("de-LI")]
        German_Liechtenstein,
        [Description("de-LU")]
        German_Luxembourg,
        [Description("dje-NE")]
        Zarma_Niger,
        [Description("dsb-DE")]
        Lower_Sorbian_Germany,
        [Description("dua-CM")]
        Duala_Cameroon,
        [Description("dv-MV")]
        Divehi_Maldives,
        [Description("dyo-SN")]
        Jola_Fonyi_Senegal,
        [Description("dz-BT")]
        Dzongkha_Bhutan,
        [Description("ebu-KE")]
        Embu_Kenya,
        [Description("ee-GH")]
        Ewe_Ghana,
        [Description("ee-TG")]
        Ewe_Togo,
        [Description("el-CY")]
        Greek_Cyprus,
        [Description("el-GR")]
        Greek_Greece,
        [Description("en-001")]
        English_World,
        [Description("en-150")]
        English_Europe,
        [Description("en-AE")]
        English_United_Arab_Emirates,
        [Description("en-AG")]
        English_Antigua__Barbuda,
        [Description("en-AI")]
        English_Anguilla,
        [Description("en-AS")]
        English_American_Samoa,
        [Description("en-AT")]
        English_Austria,
        [Description("en-AU")]
        English_Australia,
        [Description("en-BB")]
        English_Barbados,
        [Description("en-BE")]
        English_Belgium,
        [Description("en-BI")]
        English_Burundi,
        [Description("en-BM")]
        English_Bermuda,
        [Description("en-BS")]
        English_Bahamas,
        [Description("en-BW")]
        English_Botswana,
        [Description("en-BZ")]
        English_Belize,
        [Description("en-CA")]
        English_Canada,
        [Description("en-CC")]
        English_Cocos_Keeling_Islands,
        [Description("en-CH")]
        English_Switzerland,
        [Description("en-CK")]
        English_Cook_Islands,
        [Description("en-CM")]
        English_Cameroon,
        [Description("en-CX")]
        English_Christmas_Island,
        [Description("en-CY")]
        English_Cyprus,
        [Description("en-DE")]
        English_Germany,
        [Description("en-DK")]
        English_Denmark,
        [Description("en-DM")]
        English_Dominica,
        [Description("en-ER")]
        English_Eritrea,
        [Description("en-FI")]
        English_Finland,
        [Description("en-FJ")]
        English_Fiji,
        [Description("en-FK")]
        English_Falkland_Islands,
        [Description("en-FM")]
        English_Micronesia,
        [Description("en-GB")]
        English_United_Kingdom,
        [Description("en-GD")]
        English_Grenada,
        [Description("en-GG")]
        English_Guernsey,
        [Description("en-GH")]
        English_Ghana,
        [Description("en-GI")]
        English_Gibraltar,
        [Description("en-GM")]
        English_Gambia,
        [Description("en-GU")]
        English_Guam,
        [Description("en-GY")]
        English_Guyana,
        [Description("en-HK")]
        English_Hong_Kong_SAR,
        [Description("en-IE")]
        English_Ireland,
        [Description("en-IL")]
        English_Israel,
        [Description("en-IM")]
        English_Isle_of_Man,
        [Description("en-IN")]
        English_India,
        [Description("en-IO")]
        English_British_Indian_Ocean_Territory,
        [Description("en-JE")]
        English_Jersey,
        [Description("en-JM")]
        English_Jamaica,
        [Description("en-KE")]
        English_Kenya,
        [Description("en-KI")]
        English_Kiribati,
        [Description("en-KN")]
        English_St_Kitts__Nevis,
        [Description("en-KY")]
        English_Cayman_Islands,
        [Description("en-LC")]
        English_St_Lucia,
        [Description("en-LR")]
        English_Liberia,
        [Description("en-LS")]
        English_Lesotho,
        [Description("en-MG")]
        English_Madagascar,
        [Description("en-MH")]
        English_Marshall_Islands,
        [Description("en-MO")]
        English_Macao_SAR,
        [Description("en-MP")]
        English_Northern_Mariana_Islands,
        [Description("en-MS")]
        English_Montserrat,
        [Description("en-MT")]
        English_Malta,
        [Description("en-MU")]
        English_Mauritius,
        [Description("en-MW")]
        English_Malawi,
        [Description("en-MY")]
        English_Malaysia,
        [Description("en-NA")]
        English_Namibia,
        [Description("en-NF")]
        English_Norfolk_Island,
        [Description("en-NG")]
        English_Nigeria,
        [Description("en-NL")]
        English_Netherlands,
        [Description("en-NR")]
        English_Nauru,
        [Description("en-NU")]
        English_Niue,
        [Description("en-NZ")]
        English_New_Zealand,
        [Description("en-PG")]
        English_Papua_New_Guinea,
        [Description("en-PH")]
        English_Philippines,
        [Description("en-PK")]
        English_Pakistan,
        [Description("en-PN")]
        English_Pitcairn_Islands,
        [Description("en-PR")]
        English_Puerto_Rico,
        [Description("en-PW")]
        English_Palau,
        [Description("en-RW")]
        English_Rwanda,
        [Description("en-SB")]
        English_Solomon_Islands,
        [Description("en-SC")]
        English_Seychelles,
        [Description("en-SD")]
        English_Sudan,
        [Description("en-SE")]
        English_Sweden,
        [Description("en-SG")]
        English_Singapore,
        [Description("en-SH")]
        English_St_Helena_Ascension_Tristan_da_Cunha,
        [Description("en-SI")]
        English_Slovenia,
        [Description("en-SL")]
        English_Sierra_Leone,
        [Description("en-SS")]
        English_South_Sudan,
        [Description("en-SX")]
        English_Sint_Maarten,
        [Description("en-SZ")]
        English_Eswatini,
        [Description("en-TC")]
        English_Turks__Caicos_Islands,
        [Description("en-TK")]
        English_Tokelau,
        [Description("en-TO")]
        English_Tonga,
        [Description("en-TT")]
        English_Trinidad__Tobago,
        [Description("en-TV")]
        English_Tuvalu,
        [Description("en-TZ")]
        English_Tanzania,
        [Description("en-UG")]
        English_Uganda,
        [Description("en-UM")]
        English_US_Outlying_Islands,
        [Description("en-US")]
        English_United_States,
        [Description("en-US-posix")]
        English_United_States_Computer,
        [Description("en-VC")]
        English_St_Vincent__Grenadines,
        [Description("en-VG")]
        English_British_Virgin_Islands,
        [Description("en-VI")]
        English_US_Virgin_Islands,
        [Description("en-VU")]
        English_Vanuatu,
        [Description("en-WS")]
        English_Samoa,
        [Description("en-ZA")]
        English_South_Africa,
        [Description("en-ZM")]
        English_Zambia,
        [Description("en-ZW")]
        English_Zimbabwe,
        [Description("eo-001")]
        Esperanto_World,
        [Description("es-419")]
        Spanish_Latin_America,
        [Description("es-AR")]
        Spanish_Argentina,
        [Description("es-BO")]
        Spanish_Bolivia,
        [Description("es-BR")]
        Spanish_Brazil,
        [Description("es-BZ")]
        Spanish_Belize,
        [Description("es-CL")]
        Spanish_Chile,
        [Description("es-CO")]
        Spanish_Colombia,
        [Description("es-CR")]
        Spanish_Costa_Rica,
        [Description("es-CU")]
        Spanish_Cuba,
        [Description("es-DO")]
        Spanish_Dominican_Republic,
        [Description("es-EC")]
        Spanish_Ecuador,
        [Description("es-ES")]
        Spanish_Spain,
        [Description("es-GQ")]
        Spanish_Equatorial_Guinea,
        [Description("es-GT")]
        Spanish_Guatemala,
        [Description("es-HN")]
        Spanish_Honduras,
        [Description("es-MX")]
        Spanish_Mexico,
        [Description("es-NI")]
        Spanish_Nicaragua,
        [Description("es-PA")]
        Spanish_Panama,
        [Description("es-PE")]
        Spanish_Peru,
        [Description("es-PH")]
        Spanish_Philippines,
        [Description("es-PR")]
        Spanish_Puerto_Rico,
        [Description("es-PY")]
        Spanish_Paraguay,
        [Description("es-SV")]
        Spanish_El_Salvador,
        [Description("es-US")]
        Spanish_United_States,
        [Description("es-UY")]
        Spanish_Uruguay,
        [Description("es-VE")]
        Spanish_Venezuela,
        [Description("et-EE")]
        Estonian_Estonia,
        [Description("eu-ES")]
        Basque_Spain,
        [Description("ewo-CM")]
        Ewondo_Cameroon,
        [Description("prs-AF")]
        prs_Afghanistan,
        [Description("fa-IR")]
        Persian_Iran,
        [Description("ff-Latn-BF")]
        Fulah_Latin_Burkina_Faso,
        [Description("ff-Latn-CM")]
        Fulah_Latin_Cameroon,
        [Description("ff-Latn-GH")]
        Fulah_Latin_Ghana,
        [Description("ff-Latn-GM")]
        Fulah_Latin_Gambia,
        [Description("ff-Latn-GN")]
        Fulah_Latin_Guinea,
        [Description("ff-Latn-GW")]
        Fulah_Latin_Guinea_Bissau,
        [Description("ff-Latn-LR")]
        Fulah_Latin_Liberia,
        [Description("ff-Latn-MR")]
        Fulah_Latin_Mauritania,
        [Description("ff-Latn-NE")]
        Fulah_Latin_Niger,
        [Description("ff-Latn-NG")]
        Fulah_Latin_Nigeria,
        [Description("ff-Latn-SL")]
        Fulah_Latin_Sierra_Leone,
        [Description("ff-Latn-SN")]
        Fulah_Latin_Senegal,
        [Description("fi-FI")]
        Finnish_Finland,
        [Description("fil-PH")]
        Filipino_Philippines,
        [Description("fo-DK")]
        Faroese_Denmark,
        [Description("fo-FO")]
        Faroese_Faroe_Islands,
        [Description("fr-BE")]
        French_Belgium,
        [Description("fr-BF")]
        French_Burkina_Faso,
        [Description("fr-BI")]
        French_Burundi,
        [Description("fr-BJ")]
        French_Benin,
        [Description("fr-BL")]
        French_St_Barthélemy,
        [Description("fr-CA")]
        French_Canada,
        [Description("fr-CD")]
        French_Congo_DRC,
        [Description("fr-CF")]
        French_Central_African_Republic,
        [Description("fr-CG")]
        French_Congo,
        [Description("fr-CH")]
        French_Switzerland,
        [Description("fr-CI")]
        French_Côte_d_Ivoire,
        [Description("fr-CM")]
        French_Cameroon,
        [Description("fr-DJ")]
        French_Djibouti,
        [Description("fr-DZ")]
        French_Algeria,
        [Description("fr-FR")]
        French_France,
        [Description("fr-GA")]
        French_Gabon,
        [Description("fr-GF")]
        French_French_Guiana,
        [Description("fr-GN")]
        French_Guinea,
        [Description("fr-GP")]
        French_Guadeloupe,
        [Description("fr-GQ")]
        French_Equatorial_Guinea,
        [Description("fr-HT")]
        French_Haiti,
        [Description("fr-KM")]
        French_Comoros,
        [Description("fr-LU")]
        French_Luxembourg,
        [Description("fr-MA")]
        French_Morocco,
        [Description("fr-MC")]
        French_Monaco,
        [Description("fr-MF")]
        French_St_Martin,
        [Description("fr-MG")]
        French_Madagascar,
        [Description("fr-ML")]
        French_Mali,
        [Description("fr-MQ")]
        French_Martinique,
        [Description("fr-MR")]
        French_Mauritania,
        [Description("fr-MU")]
        French_Mauritius,
        [Description("fr-NC")]
        French_New_Caledonia,
        [Description("fr-NE")]
        French_Niger,
        [Description("fr-PF")]
        French_French_Polynesia,
        [Description("fr-PM")]
        French_St_Pierre__Miquelon,
        [Description("fr-RE")]
        French_Réunion,
        [Description("fr-RW")]
        French_Rwanda,
        [Description("fr-SC")]
        French_Seychelles,
        [Description("fr-SN")]
        French_Senegal,
        [Description("fr-SY")]
        French_Syria,
        [Description("fr-TD")]
        French_Chad,
        [Description("fr-TG")]
        French_Togo,
        [Description("fr-TN")]
        French_Tunisia,
        [Description("fr-VU")]
        French_Vanuatu,
        [Description("fr-WF")]
        French_Wallis__Futuna,
        [Description("fr-YT")]
        French_Mayotte,
        [Description("fur-IT")]
        Friulian_Italy,
        [Description("fy-NL")]
        Western_Frisian_Netherlands,
        [Description("ga-IE")]
        Irish_Ireland,
        [Description("gd-GB")]
        Scottish_Gaelic_United_Kingdom,
        [Description("gl-ES")]
        Galician_Spain,
        [Description("gn-PY")]
        Guarani_Paraguay,
        [Description("gsw-CH")]
        Swiss_German_Switzerland,
        [Description("gsw-FR")]
        Swiss_German_France,
        [Description("gsw-LI")]
        Swiss_German_Liechtenstein,
        [Description("gu-IN")]
        Gujarati_India,
        [Description("guz-KE")]
        Gusii_Kenya,
        [Description("gv-IM")]
        Manx_Isle_of_Man,
        [Description("ha-Latn-GH")]
        Hausa_Latin_Ghana,
        [Description("ha-Latn-NE")]
        Hausa_Latin_Niger,
        [Description("ha-Latn-NG")]
        Hausa_Latin_Nigeria,
        [Description("haw-US")]
        Hawaiian_United_States,
        [Description("he-IL")]
        Hebrew_Israel,
        [Description("hi-IN")]
        Hindi_India,
        [Description("hr-BA")]
        Croatian_Bosnia__Herzegovina,
        [Description("hr-HR")]
        Croatian_Croatia,
        [Description("hsb-DE")]
        Upper_Sorbian_Germany,
        [Description("hu-HU")]
        Hungarian_Hungary,
        [Description("hy-AM")]
        Armenian_Armenia,
        [Description("ia-001")]
        Interlingua_World,
        [Description("id-ID")]
        Indonesian_Indonesia,
        [Description("ig-NG")]
        Igbo_Nigeria,
        [Description("ii-CN")]
        Yi_China,
        [Description("is-IS")]
        Icelandic_Iceland,
        [Description("it-CH")]
        Italian_Switzerland,
        [Description("it-IT")]
        Italian_Italy,
        [Description("it-SM")]
        Italian_San_Marino,
        [Description("it-VA")]
        Italian_Vatican_City,
        [Description("iu-CA")]
        Inuktitut_Canada,
        [Description("iu-Latn-CA")]
        Inuktitut_Latin_Canada,
        [Description("ja-JP")]
        Japanese_Japan,
        [Description("jgo-CM")]
        Ngomba_Cameroon,
        [Description("jmc-TZ")]
        Machame_Tanzania,
        [Description("jv-Latn-ID")]
        Javanese_Latin_Indonesia,
        [Description("ka-GE")]
        Georgian_Georgia,
        [Description("kab-DZ")]
        Kabyle_Algeria,
        [Description("kam-KE")]
        Kamba_Kenya,
        [Description("kde-TZ")]
        Makonde_Tanzania,
        [Description("kea-CV")]
        Kabuverdianu_Cabo_Verde,
        [Description("khq-ML")]
        Koyra_Chiini_Mali,
        [Description("ki-KE")]
        Kikuyu_Kenya,
        [Description("kk-KZ")]
        Kazakh_Kazakhstan,
        [Description("kkj-CM")]
        Kako_Cameroon,
        [Description("kl-GL")]
        Kalaallisut_Greenland,
        [Description("kln-KE")]
        Kalenjin_Kenya,
        [Description("km-KH")]
        Khmer_Cambodia,
        [Description("kn-IN")]
        Kannada_India,
        [Description("ko-KP")]
        Korean_North_Korea,
        [Description("ko-KR")]
        Korean_Korea,
        [Description("kok-IN")]
        Konkani_India,
        [Description("ks-Arab-IN")]
        Kashmiri_Arabic_India,
        [Description("ksb-TZ")]
        Shambala_Tanzania,
        [Description("ksf-CM")]
        Bafia_Cameroon,
        [Description("ksh-DE")]
        Colognian_Germany,
        [Description("kw-GB")]
        Cornish_United_Kingdom,
        [Description("ky-KG")]
        Kyrgyz_Kyrgyzstan,
        [Description("lag-TZ")]
        Langi_Tanzania,
        [Description("lb-LU")]
        Luxembourgish_Luxembourg,
        [Description("lg-UG")]
        Ganda_Uganda,
        [Description("lkt-US")]
        Lakota_United_States,
        [Description("ln-AO")]
        Lingala_Angola,
        [Description("ln-CD")]
        Lingala_Congo_DRC,
        [Description("ln-CF")]
        Lingala_Central_African_Republic,
        [Description("ln-CG")]
        Lingala_Congo,
        [Description("lo-LA")]
        Lao_Laos,
        [Description("lrc-IQ")]
        Northern_Luri_Iraq,
        [Description("lrc-IR")]
        Northern_Luri_Iran,
        [Description("lt-LT")]
        Lithuanian_Lithuania,
        [Description("lu-CD")]
        Luba_Katanga_Congo_DRC,
        [Description("luo-KE")]
        Luo_Kenya,
        [Description("luy-KE")]
        Luyia_Kenya,
        [Description("lv-LV")]
        Latvian_Latvia,
        [Description("mas-KE")]
        Masai_Kenya,
        [Description("mas-TZ")]
        Masai_Tanzania,
        [Description("mer-KE")]
        Meru_Kenya,
        [Description("mfe-MU")]
        Morisyen_Mauritius,
        [Description("mg-MG")]
        Malagasy_Madagascar,
        [Description("mgh-MZ")]
        Makhuwa_Meetto_Mozambique,
        [Description("mgo-CM")]
        Metaʼ_Cameroon,
        [Description("mi-NZ")]
        Maori_New_Zealand,
        [Description("mk-MK")]
        Macedonian_North_Macedonia,
        [Description("ml-IN")]
        Malayalam_India,
        [Description("mn-MN")]
        Mongolian_Mongolia,
        [Description("mn-Mong-CN")]
        Mongolian_Mongolian_China,
        [Description("mn-Mong-MN")]
        Mongolian_Mongolian_Mongolia,
        [Description("moh-CA")]
        Mohawk_Canada,
        [Description("mr-IN")]
        Marathi_India,
        [Description("ms-BN")]
        Malay_Brunei,
        [Description("ms-MY")]
        Malay_Malaysia,
        [Description("ms-SG")]
        Malay_Singapore,
        [Description("mt-MT")]
        Maltese_Malta,
        [Description("mua-CM")]
        Mundang_Cameroon,
        [Description("my-MM")]
        Burmese_Myanmar,
        [Description("mzn-IR")]
        Mazanderani_Iran,
        [Description("naq-NA")]
        Nama_Namibia,
        [Description("nb-NO")]
        Norwegian_Bokmål_Norway,
        [Description("nb-SJ")]
        Norwegian_Bokmål_Svalbard__Jan_Mayen,
        [Description("nd-ZW")]
        North_Ndebele_Zimbabwe,
        [Description("nds-DE")]
        Low_German_Germany,
        [Description("nds-NL")]
        Low_German_Netherlands,
        [Description("ne-IN")]
        Nepali_India,
        [Description("ne-NP")]
        Nepali_Nepal,
        [Description("nl-AW")]
        Dutch_Aruba,
        [Description("nl-BE")]
        Dutch_Belgium,
        [Description("nl-BQ")]
        Dutch_Bonaire_Sint_Eustatius_and_Saba,
        [Description("nl-CW")]
        Dutch_Curaçao,
        [Description("nl-NL")]
        Dutch_Netherlands,
        [Description("nl-SR")]
        Dutch_Suriname,
        [Description("nl-SX")]
        Dutch_Sint_Maarten,
        [Description("nmg-CM")]
        Kwasio_Cameroon,
        [Description("nn-NO")]
        Norwegian_Nynorsk_Norway,
        [Description("nnh-CM")]
        Ngiemboon_Cameroon,
        [Description("nqo-GN")]
        NKo_Guinea,
        [Description("nr-ZA")]
        South_Ndebele_South_Africa,
        [Description("nso-ZA")]
        Sesotho_sa_Leboa_South_Africa,
        [Description("nus-SS")]
        Nuer_South_Sudan,
        [Description("nyn-UG")]
        Nyankole_Uganda,
        [Description("oc-FR")]
        Occitan_France,
        [Description("om-ET")]
        Oromo_Ethiopia,
        [Description("om-KE")]
        Oromo_Kenya,
        [Description("or-IN")]
        Odia_India,
        [Description("os-GE")]
        Ossetic_Georgia,
        [Description("os-RU")]
        Ossetic_Russia,
        [Description("pa-Arab-PK")]
        Punjabi_Arabic_Pakistan,
        [Description("pa-IN")]
        Punjabi_India,
        [Description("pl-PL")]
        Polish_Poland,
        [Description("prg-001")]
        Prussian_World,
        [Description("ps-AF")]
        Pashto_Afghanistan,
        [Description("ps-PK")]
        Pashto_Pakistan,
        [Description("pt-AO")]
        Portuguese_Angola,
        [Description("pt-BR")]
        Portuguese_Brazil,
        [Description("pt-CH")]
        Portuguese_Switzerland,
        [Description("pt-CV")]
        Portuguese_Cabo_Verde,
        [Description("pt-GQ")]
        Portuguese_Equatorial_Guinea,
        [Description("pt-GW")]
        Portuguese_Guinea_Bissau,
        [Description("pt-LU")]
        Portuguese_Luxembourg,
        [Description("pt-MO")]
        Portuguese_Macao_SAR,
        [Description("pt-MZ")]
        Portuguese_Mozambique,
        [Description("pt-PT")]
        Portuguese_Portugal,
        [Description("pt-ST")]
        Portuguese_São_Tomé__Príncipe,
        [Description("pt-TL")]
        Portuguese_Timor_Leste,
        [Description("quz-BO")]
        quz_Bolivia,
        [Description("quz-EC")]
        quz_Ecuador,
        [Description("quz-PE")]
        quz_Peru,
        [Description("quc-GT")]
        Kʼicheʼ_Guatemala,
        [Description("rm-CH")]
        Romansh_Switzerland,
        [Description("rn-BI")]
        Rundi_Burundi,
        [Description("ro-MD")]
        Romanian_Moldova,
        [Description("ro-RO")]
        Romanian_Romania,
        [Description("rof-TZ")]
        Rombo_Tanzania,
        [Description("ru-BY")]
        Russian_Belarus,
        [Description("ru-KG")]
        Russian_Kyrgyzstan,
        [Description("ru-KZ")]
        Russian_Kazakhstan,
        [Description("ru-MD")]
        Russian_Moldova,
        [Description("ru-RU")]
        Russian_Russia,
        [Description("ru-UA")]
        Russian_Ukraine,
        [Description("rw-RW")]
        Kinyarwanda_Rwanda,
        [Description("rwk-TZ")]
        Rwa_Tanzania,
        [Description("sa-IN")]
        Sanskrit_India,
        [Description("sah-RU")]
        Sakha_Russia,
        [Description("saq-KE")]
        Samburu_Kenya,
        [Description("sbp-TZ")]
        Sangu_Tanzania,
        [Description("sd-Arab-PK")]
        Sindhi_Arabic_Pakistan,
        [Description("se-FI")]
        Northern_Sami_Finland,
        [Description("se-NO")]
        Northern_Sami_Norway,
        [Description("se-SE")]
        Northern_Sami_Sweden,
        [Description("seh-MZ")]
        Sena_Mozambique,
        [Description("ses-ML")]
        Koyraboro_Senni_Mali,
        [Description("sg-CF")]
        Sango_Central_African_Republic,
        [Description("shi-Latn-MA")]
        Tachelhit_Latin_Morocco,
        [Description("shi-Tfng-MA")]
        Tachelhit_Tifinagh_Morocco,
        [Description("si-LK")]
        Sinhala_Sri_Lanka,
        [Description("sk-SK")]
        Slovak_Slovakia,
        [Description("sl-SI")]
        Slovenian_Slovenia,
        [Description("sma-NO")]
        Southern_Sami_Norway,
        [Description("sma-SE")]
        Southern_Sami_Sweden,
        [Description("smj-NO")]
        Lule_Sami_Norway,
        [Description("smj-SE")]
        Lule_Sami_Sweden,
        [Description("smn-FI")]
        Inari_Sami_Finland,
        [Description("sms-FI")]
        Skolt_Sami_Finland,
        [Description("sn-Latn-ZW")]
        Shona_Latin_Zimbabwe,
        [Description("so-DJ")]
        Somali_Djibouti,
        [Description("so-ET")]
        Somali_Ethiopia,
        [Description("so-KE")]
        Somali_Kenya,
        [Description("so-SO")]
        Somali_Somalia,
        [Description("sq-AL")]
        Albanian_Albania,
        [Description("sq-MK")]
        Albanian_North_Macedonia,
        [Description("sq-XK")]
        Albanian_Kosovo,
        [Description("sr-Cyrl-BA")]
        Serbian_Cyrillic_Bosnia__Herzegovina,
        [Description("sr-Cyrl-ME")]
        Serbian_Cyrillic_Montenegro,
        [Description("sr-Cyrl-RS")]
        Serbian_Cyrillic_Serbia,
        [Description("sr-Cyrl-XK")]
        Serbian_Cyrillic_Kosovo,
        [Description("sr-Latn-BA")]
        Serbian_Latin_Bosnia__Herzegovina,
        [Description("sr-Latn-ME")]
        Serbian_Latin_Montenegro,
        [Description("sr-Latn-RS")]
        Serbian_Latin_Serbia,
        [Description("sr-Latn-XK")]
        Serbian_Latin_Kosovo,
        [Description("ss-SZ")]
        siSwati_Eswatini,
        [Description("ss-ZA")]
        siSwati_South_Africa,
        [Description("ssy-ER")]
        Saho_Eritrea,
        [Description("st-LS")]
        Sesotho_Lesotho,
        [Description("st-ZA")]
        Sesotho_South_Africa,
        [Description("sv-AX")]
        Swedish_Åland_Islands,
        [Description("sv-FI")]
        Swedish_Finland,
        [Description("sv-SE")]
        Swedish_Sweden,
        [Description("sw-CD")]
        Kiswahili_Congo_DRC,
        [Description("sw-KE")]
        Kiswahili_Kenya,
        [Description("sw-TZ")]
        Kiswahili_Tanzania,
        [Description("sw-UG")]
        Kiswahili_Uganda,
        [Description("syr-SY")]
        Syriac_Syria,
        [Description("ta-IN")]
        Tamil_India,
        [Description("ta-LK")]
        Tamil_Sri_Lanka,
        [Description("ta-MY")]
        Tamil_Malaysia,
        [Description("ta-SG")]
        Tamil_Singapore,
        [Description("te-IN")]
        Telugu_India,
        [Description("teo-KE")]
        Teso_Kenya,
        [Description("teo-UG")]
        Teso_Uganda,
        [Description("tg-Cyrl-TJ")]
        Tajik_Cyrillic_Tajikistan,
        [Description("th-TH")]
        Thai_Thailand,
        [Description("ti-ER")]
        Tigrinya_Eritrea,
        [Description("ti-ET")]
        Tigrinya_Ethiopia,
        [Description("tig-ER")]
        Tigre_Eritrea,
        [Description("tk-TM")]
        Turkmen_Turkmenistan,
        [Description("tn-BW")]
        Setswana_Botswana,
        [Description("tn-ZA")]
        Setswana_South_Africa,
        [Description("to-TO")]
        Tongan_Tonga,
        [Description("tr-CY")]
        Turkish_Cyprus,
        [Description("tr-TR")]
        Turkish_Turkey,
        [Description("ts-ZA")]
        Xitsonga_South_Africa,
        [Description("tt-RU")]
        Tatar_Russia,
        [Description("twq-NE")]
        Tasawaq_Niger,
        [Description("tzm-Latn-MA")]
        Central_Atlas_Tamazight_Latin_Morocco,
        [Description("ug-CN")]
        Uyghur_China,
        [Description("uk-UA")]
        Ukrainian_Ukraine,
        [Description("ur-IN")]
        Urdu_India,
        [Description("ur-PK")]
        Urdu_Pakistan,
        [Description("uz-Arab-AF")]
        Uzbek_Arabic_Afghanistan,
        [Description("uz-Cyrl-UZ")]
        Uzbek_Cyrillic_Uzbekistan,
        [Description("uz-Latn-UZ")]
        Uzbek_Latin_Uzbekistan,
        [Description("vai-Latn-LR")]
        Vai_Latin_Liberia,
        [Description("vai-Vaii-LR")]
        Vai_Vai_Liberia,
        [Description("ve-ZA")]
        Venda_South_Africa,
        [Description("vi-VN")]
        Vietnamese_Vietnam,
        [Description("vo-001")]
        Volapük_World,
        [Description("vun-TZ")]
        Vunjo_Tanzania,
        [Description("wae-CH")]
        Walser_Switzerland,
        [Description("wal-ET")]
        Wolaytta_Ethiopia,
        [Description("wo-SN")]
        Wolof_Senegal,
        [Description("xh-ZA")]
        isiXhosa_South_Africa,
        [Description("xog-UG")]
        Soga_Uganda,
        [Description("yav-CM")]
        Yangben_Cameroon,
        [Description("yi-001")]
        Yiddish_World,
        [Description("yo-BJ")]
        Yoruba_Benin,
        [Description("yo-NG")]
        Yoruba_Nigeria,
        [Description("zgh-Tfng-MA")]
        Standard_Moroccan_Tamazight_Tifinagh_Morocco,
        [Description("zh-CN")]
        Chinese_China,
        [Description("zh-Hans-HK")]
        Chinese_Simplified_Hong_Kong_SAR,
        [Description("zh-Hans-MO")]
        Chinese_Simplified_Macao_SAR,
        [Description("zh-SG")]
        Chinese_Singapore,
        [Description("zh-HK")]
        Chinese_Hong_Kong_SAR,
        [Description("zh-MO")]
        Chinese_Macao_SAR,
        [Description("zh-TW")]
        Chinese_Taiwan,
        [Description("zu-ZA")]
        isiZulu_South_Africa,
    }
}
